In [1]:
import pandas as pd

In [2]:
df_items = pd.read_csv('items.csv', sep='|')
df_items.head(20)

,itemID,title,author,publisher,main topic,subtopics
0,21310,Princess Poppy: The Big Mix Up,Janey Louise Jones,Penguin Random House Children's UK,YFB,[5AH]
1,73018,Einfach zeichnen! Step by Step,Wiebke Krabbe,Schwager und Steinlein,AGZ,"[5AJ,AGZ,WFA,YBG,YBL,YNA,YPA]"
2,19194,Red Queen 1,Victoria Aveyard,Orion Publishing Group,YFH,"[5AP,FBA]"
3,40250,Meine Kindergarten-Freunde (Pirat),NaN,Ars Edition GmbH,YB,"[5AC,5AD,YBG,YBL,YF]"
4,46107,Mein großes Schablonen-Buch - Wilde Tiere,Elizabeth Golding,Edition Michael Fischer,WFTM,"[WD,WFTM,YBG,YBL,YBLD,YBLN1]"
5,34217,Ewig geliebt,J. R. Ward,Heyne Taschenbuch,FMR,"[1KBB-US-NAK,FMX,FRX,3MRBF]"
6,31436,Meine Sticker-Tiere,NaN,Ars Edition GmbH,YBG,"[5AD,YBG,YBLL]"
7,14576,Unsterblich 01 - Tor der Dämmerung,Julie Kagawa,Heyne Taschenbuch,YFE,"[5AQ,FM,YFE,YFH]"
8,17731,Unsterblich 02 - Tor der Nacht,Julie Kagawa,Heyne Taschenbuch,YFH,"[5AQ,FM,YFE,YFH]"
9,58723,Pedro und die Bettler von Cartagena,Ursula Hasler,dtv Verlagsgesellschaft,YFB,"[5AM,1KLSC]"
10,73124,Freundebuch - Einhorn-Paradies - Meine Freunde,NaN,Coppenrath F,YZG,"[5JA,YBG,YBL,YFH,YZS]"
11,33976,Die Haushörerin,Anna Lummfeld,Books on Demand,FMR,"[1DFG-DE-VH,FMR,FMX,FRD]"
12,2408,Reiter der schwarzen Sonne,Swen Harder,Mantikore Verlag,FMB,"[5AN,WDHW]"
13,30277,WAS IST WAS Quiz Autos,Lorena Lehnert,Tessloff Verlag,YNV,"[5AJ,YBL]"
14,29508,WAS IST WAS Quiz Länder der Welt,Carolin Langbein,Tessloff Verlag,YNV,"[5AJ,YBL]"
15,75659,WAS IST WAS Quiz Fußball,Lorena Lehnert,Tessloff Verlag,YNWD1,"[5AJ,2ACG,SFBC,WDKX,YBL,YNVP,YZG]"
16,55699,Spring in eine Pfütze! Mein perfekter Frühling...,ViktoriaSarina,CE Community Editions,YNVP,"[YBG,YBL,YNVP,YZS]"
17,62433,Und dann kamst du,Heike Abidi,Oetinger Taschenbuch GmbH,YXHL,"[5AQ,5JA,DND,YFM,YXHL]"
18,72603,"Ich hab einen Freund, der ist Astronaut",Ralf Butschkow,Carlsen Verlag GmbH,YBCS,"[5AC,4CA,YBL,YF,YNK,YNMH,YNNZ,YNTR]"
19,11989,Vampire Academy 06,Richelle Mead,LYX,FMR,"[5AQ,FMB,FMR,FMX,FRT]"

In [3]:
df_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78030 entries, 0 to 78029
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   itemID      78030 non-null  int64
 1   title       78030 non-null  object
 2   author      74790 non-null  object
 3   publisher   78021 non-null  object
 4   main topic  77772 non-null  object
 5   subtopics   78029 non-null  object
dtypes: int64(1), object(5)
memory usage: 3.6+ MB

In [4]:
df_items.loc[df_items['author'].isna()]

,itemID,title,author,publisher,main topic,subtopics
3,40250,Meine Kindergarten-Freunde (Pirat),NaN,Ars Edition GmbH,YB,"[5AC,5AD,YBG,YBL,YF]"
6,31436,Meine Sticker-Tiere,NaN,Ars Edition GmbH,YBG,"[5AD,YBG,YBLL]"
10,73124,Freundebuch - Einhorn-Paradies - Meine Freunde,NaN,Coppenrath F,YZG,"[5JA,YBG,YBL,YFH,YZS]"
28,63166,Fingerstempel-Spaß Kunterbunt,NaN,Ars Edition GmbH,YBLD,"[5AD,YBG,YBLD]"
29,44220,Fingerstempel-Spaß Tiere,NaN,Ars Edition GmbH,YBG,"[5AD,YBG,YBLD,YBLL]"
...,...,...,...,...,...,...
77788,37942,Perry Rhodan 109. Das Loch im Universum,NaN,MOEWIG,FL,[]
77864,4022,Iron Man Armoured Avenger,NaN,Panini Publishing Ltd,XADC,[YF]
77869,30445,Find Out,NaN,Books on Demand,FM,[FL]
77876,45554,The Eyes of Despero!,NaN,GROSSET DUNLAP,YFZZ,[YFC]
77936,45764,Despicable Me: The Junior Novel,NaN,LITTLE BROWN & CO,YFC,[]

In [5]:
df_items.loc[df_items['author'].isna(),'author'] = "other"
df_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78030 entries, 0 to 78029
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   itemID      78030 non-null  int64
 1   title       78030 non-null  object
 2   author      78030 non-null  object
 3   publisher   78021 non-null  object
 4   main topic  77772 non-null  object
 5   subtopics   78029 non-null  object
dtypes: int64(1), object(5)
memory usage: 3.6+ MB

In [6]:
df_items.loc[df_items['publisher'].isna()].shape

(9, 6)

In [7]:
df_items.loc[df_items['subtopics'] == '[]'].shape
# 36904

(36904, 6)

In [8]:
df_items.loc[(df_items['main topic'].isna()) ]
# 258

,itemID,title,author,publisher,main topic,subtopics
182,6798,Kernstaub,Marie Graßhoff,Drachenmond Verlag,NaN,[FM]
211,67006,Mein erstes Feuerwehr-Bastelbuch,other,"Coppenrath, Münster",NaN,[5AC]
536,38541,Näh mit! Die Kindernähschule,Ina Andresen,Frech Verlag GmbH,NaN,[5AH]
647,25076,Star Trek - New Frontier: Mehr als Götter,Peter David,Cross Cult,NaN,"[FLS,FLU]"
1236,27457,Retreat: Stirb lachend!,"Joe McKinney, Craig DiLouie, Steven Knight",Luzifer,NaN,"[1KBB,FKM,FLQ]"
...,...,...,...,...,...,...
64281,44390,Eleha - Aufbruch,Sonja Girisch,Books on Demand,NaN,[FRM]
75807,21505,Vamps and the City,Kerrelyn Sparks,MIRA Taschenbuch,NaN,[FMR]
76628,40959,Wie das Schwein zum Tanze ging,Michael Köhlmeier,DTV,NaN,[5AM]
77261,64864,Die Eingeborenen,Karsten Kruschel,Wurdack,NaN,"[FLS,FLU]"
77808,6965,Die Magier von Montparnasse,Oliver Plaschka,Klett-Cotta,NaN,"[1DDF-FR-LAA,FMH,3MPBGH]"

In [9]:
df_items['main topic'].unique

<bound method Series.unique of 0         YFB
1         AGZ
2         YFH
3          YB
4        WFTM
         ...
78025     YFA
78026     FMB
78027     YFU
78028     YFC
78029      FL
Name: main topic, Length: 78030, dtype: object>

In [10]:
# drop nan publisher\
df_items['publisher'].dropna(axis=0, inplace=True)
df_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78030 entries, 0 to 78029
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   itemID      78030 non-null  int64
 1   title       78030 non-null  object
 2   author      78030 non-null  object
 3   publisher   78021 non-null  object
 4   main topic  77772 non-null  object
 5   subtopics   78029 non-null  object
dtypes: int64(1), object(5)
memory usage: 3.6+ MB

In [11]:


for index,item in df_items.iterrows():
    if item['main topic'] == None:
        
        df_items[index]['main topic'] = df_items[index]['subtopic'][0]

In [12]:
df_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78030 entries, 0 to 78029
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   itemID      78030 non-null  int64
 1   title       78030 non-null  object
 2   author      78030 non-null  object
 3   publisher   78021 non-null  object
 4   main topic  77772 non-null  object
 5   subtopics   78029 non-null  object
dtypes: int64(1), object(5)
memory usage: 3.6+ MB

In [15]:
df_items.loc[(df_items['main topic'].isna()) ]

,itemID,title,author,publisher,main topic,subtopics
182,6798,Kernstaub,Marie Graßhoff,Drachenmond Verlag,NaN,[FM]
211,67006,Mein erstes Feuerwehr-Bastelbuch,other,"Coppenrath, Münster",NaN,[5AC]
536,38541,Näh mit! Die Kindernähschule,Ina Andresen,Frech Verlag GmbH,NaN,[5AH]
647,25076,Star Trek - New Frontier: Mehr als Götter,Peter David,Cross Cult,NaN,"[FLS,FLU]"
1236,27457,Retreat: Stirb lachend!,"Joe McKinney, Craig DiLouie, Steven Knight",Luzifer,NaN,"[1KBB,FKM,FLQ]"
...,...,...,...,...,...,...
64281,44390,Eleha - Aufbruch,Sonja Girisch,Books on Demand,NaN,[FRM]
75807,21505,Vamps and the City,Kerrelyn Sparks,MIRA Taschenbuch,NaN,[FMR]
76628,40959,Wie das Schwein zum Tanze ging,Michael Köhlmeier,DTV,NaN,[5AM]
77261,64864,Die Eingeborenen,Karsten Kruschel,Wurdack,NaN,"[FLS,FLU]"
77808,6965,Die Magier von Montparnasse,Oliver Plaschka,Klett-Cotta,NaN,"[1DDF-FR-LAA,FMH,3MPBGH]"

In [13]:
df_transaction = pd.read_csv('transactions.csv', sep='|')
df_transaction.head(10)

   sessionID  itemID  click  basket  order
0          0   21310      1       0      0
1          1   73018      1       0      0
2          2   19194      1       0      0
3          3   40250      1       0      0
4          4   46107      1       0      0
5          5   34217      1       0      0
6          6   31436      1       0      0
7          7   14576      1       1      0
8          7   17731      2       1      0
9          8   58723      1       0      0

In [14]:
df_transaction.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365143 entries, 0 to 365142
Data columns (total 5 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   sessionID  365143 non-null  int64
 1   itemID     365143 non-null  int64
 2   click      365143 non-null  int64
 3   basket     365143 non-null  int64
 4   order      365143 non-null  int64
dtypes: int64(5)
memory usage: 13.9 MB